In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Mall_Customers.csv")

In [3]:
dataset.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
dataset.isnull().any()

CustomerID                False
Genre                     False
Age                       False
Annual Income (k$)        False
Spending Score (1-100)    False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Genre"]=le.fit_transform(dataset["Genre"])

In [6]:
dataset.head()

   CustomerID  Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1      1   19                  15                      39
1           2      1   21                  15                      81
2           3      0   20                  16                       6
3           4      0   23                  16                      77
4           5      0   31                  17                      40

In [7]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4].values

In [8]:
x

array([[  1,   1,  19,  15],
       [  2,   1,  21,  15],
       [  3,   0,  20,  16],
       [  4,   0,  23,  16],
       [  5,   0,  31,  17],
       [  6,   0,  22,  17],
       [  7,   0,  35,  18],
       [  8,   0,  23,  18],
       [  9,   1,  64,  19],
       [ 10,   0,  30,  19],
       [ 11,   1,  67,  19],
       [ 12,   0,  35,  19],
       [ 13,   0,  58,  20],
       [ 14,   0,  24,  20],
       [ 15,   1,  37,  20],
       [ 16,   1,  22,  20],
       [ 17,   0,  35,  21],
       [ 18,   1,  20,  21],
       [ 19,   1,  52,  23],
       [ 20,   0,  35,  23],
       [ 21,   1,  35,  24],
       [ 22,   1,  25,  24],
       [ 23,   0,  46,  25],
       [ 24,   1,  31,  25],
       [ 25,   0,  54,  28],
       [ 26,   1,  29,  28],
       [ 27,   0,  45,  28],
       [ 28,   1,  35,  28],
       [ 29,   0,  40,  29],
       [ 30,   0,  23,  29],
       [ 31,   1,  60,  30],
       [ 32,   0,  21,  30],
       [ 33,   1,  53,  33],
       [ 34,   1,  18,  33],
       [ 35,   0,  49,  33],
       [ 36,   0,  21,  33],
       [ 37,   0,  42,  34],
       [ 38,   0,  30,  34],
       [ 39,   0,  36,  37],
       [ 40,   0,  20,  37],
       [ 41,   0,  65,  38],
       [ 42,   1,  24,  38],
       [ 43,   1,  48,  39],
       [ 44,   0,  31,  39],
       [ 45,   0,  49,  39],
       [ 46,   0,  24,  39],
       [ 47,   0,  50,  40],
       [ 48,   0,  27,  40],
       [ 49,   0,  29,  40],
       [ 50,   0,  31,  40],
       [ 51,   0,  49,  42],
       [ 52,   1,  33,  42],
       [ 53,   0,  31,  43],
       [ 54,   1,  59,  43],
       [ 55,   0,  50,  43],
       [ 56,   1,  47,  43],
       [ 57,   0,  51,  44],
       [ 58,   1,  69,  44],
       [ 59,   0,  27,  46],
       [ 60,   1,  53,  46],
       [ 61,   1,  70,  46],
       [ 62,   1,  19,  46],
       [ 63,   0,  67,  47],
       [ 64,   0,  54,  47],
       [ 65,   1,  63,  48],
       [ 66,   1,  18,  48],
       [ 67,   0,  43,  48],
       [ 68,   0,  68,  48],
       [ 69,   1,  19,  48],
       [ 70,   0,  32,  48],
       [ 71,   1,  70,  49],
       [ 72,   0,  47,  49],
       [ 73,   0,  60,  50],
       [ 74,   0,  60,  50],
       [ 75,   1,  59,  54],
       [ 76,   1,  26,  54],
       [ 77,   0,  45,  54],
       [ 78,   1,  40,  54],
       [ 79,   0,  23,  54],
       [ 80,   0,  49,  54],
       [ 81,   1,  57,  54],
       [ 82,   1,  38,  54],
       [ 83,   1,  67,  54],
       [ 84,   0,  46,  54],
       [ 85,   0,  21,  54],
       [ 86,   1,  48,  54],
       [ 87,   0,  55,  57],
       [ 88,   0,  22,  57],
       [ 89,   0,  34,  58],
       [ 90,   0,  50,  58],
       [ 91,   0,  68,  59],
       [ 92,   1,  18,  59],
       [ 93,   1,  48,  60],
       [ 94,   0,  40,  60],
       [ 95,   0,  32,  60],
       [ 96,   1,  24,  60],
       [ 97,   0,  47,  60],
       [ 98,   0,  27,  60],
       [ 99,   1,  48,  61],
       [100,   1,  20,  61],
       [101,   0,  23,  62],
       [102,   0,  49,  62],
       [103,   1,  67,  62],
       [104,   1,  26,  62],
       [105,   1,  49,  62],
       [106,   0,  21,  62],
       [107,   0,  66,  63],
       [108,   1,  54,  63],
       [109,   1,  68,  63],
       [110,   1,  66,  63],
       [111,   1,  65,  63],
       [112,   0,  19,  63],
       [113,   0,  38,  64],
       [114,   1,  19,  64],
       [115,   0,  18,  65],
       [116,   0,  19,  65],
       [117,   0,  63,  65],
       [118,   0,  49,  65],
       [119,   0,  51,  67],
       [120,   0,  50,  67],
       [121,   1,  27,  67],
       [122,   0,  38,  67],
       [123,   0,  40,  69],
       [124,   1,  39,  69],
       [125,   0,  23,  70],
       [126,   0,  31,  70],
       [127,   1,  43,  71],
       [128,   1,  40,  71],
       [129,   1,  59,  71],
       [130,   1,  38,  71],
       [131,   1,  47,  71],
       [132,   1,  39,  71],
       [133,   0,  25,  72],
       [134,   0,  31,  72],
       [135,   1,  20,  73],
       [136,   0,  29,  73],
       [137,   0,  44,  73],
       [138,   1,  32,  73],
       [139,   1,  19,  74],
       [140,   0,  35,  74],
       [141,   0,  57,  75],
       [142,   1,  32,  75],
       [143,   0,  28,  76],
       [144,   0,  32,  76],
       [145,   1,  25,  77],
       [146,   1,  28,  77],
       [147,   1,  48,  77],
       [148,   0,  32,  77],
       [149,   0,  34,  78],
       [150,   1,  34,  78],
       [151,   1,  43,  78],
       [152,   1,  39,  78],
       [153,   0,  44,  78],
       [154,   0,  38,  78],
       [155,   0,  47,  78],
       [156,   0,  27,  78],
       [157,   1,  37,  78],
       [158,   0,  30,  78],
       [159,   1,  34,  78],
       [160,   0,  30,  78],
       [161,   0,  56,  79],
       [162,   0,  29,  79],
       [163,   1,  19,  81],
       [164,   0,  31,  81],
       [165,   1,  50,  85],
       [166,   0,  36,  85],
       [167,   1,  42,  86],
       [168,   0,  33,  86],
       [169,   0,  36,  87],
       [170,   1,  32,  87],
       [171,   1,  40,  87],
       [172,   1,  28,  87],
       [173,   1,  36,  87],
       [174,   1,  36,  87],
       [175,   0,  52,  88],
       [176,   0,  30,  88],
       [177,   1,  58,  88],
       [178,   1,  27,  88],
       [179,   1,  59,  93],
       [180,   1,  35,  93],
       [181,   0,  37,  97],
       [182,   0,  32,  97],
       [183,   1,  46,  98],
       [184,   0,  29,  98],
       [185,   0,  41,  99],
       [186,   1,  30,  99],
       [187,   0,  54, 101],
       [188,   1,  28, 101],
       [189,   0,  41, 103],
       [190,   0,  36, 103],
       [191,   0,  34, 103],
       [192,   0,  32, 103],
       [193,   1,  33, 113],
       [194,   0,  38, 113],
       [195,   0,  47, 120],
       [196,   0,  35, 120],
       [197,   0,  45, 126],
       [198,   1,  32, 126],
       [199,   1,  32, 137],
       [200,   1,  30, 137]], dtype=int64)

In [9]:
y

array([39, 81,  6, 77, 40, 76,  6, 94,  3, 72, 14, 99, 15, 77, 13, 79, 35,
       66, 29, 98, 35, 73,  5, 73, 14, 82, 32, 61, 31, 87,  4, 73,  4, 92,
       14, 81, 17, 73, 26, 75, 35, 92, 36, 61, 28, 65, 55, 47, 42, 42, 52,
       60, 54, 60, 45, 41, 50, 46, 51, 46, 56, 55, 52, 59, 51, 59, 50, 48,
       59, 47, 55, 42, 49, 56, 47, 54, 53, 48, 52, 42, 51, 55, 41, 44, 57,
       46, 58, 55, 60, 46, 55, 41, 49, 40, 42, 52, 47, 50, 42, 49, 41, 48,
       59, 55, 56, 42, 50, 46, 43, 48, 52, 54, 42, 46, 48, 50, 43, 59, 43,
       57, 56, 40, 58, 91, 29, 77, 35, 95, 11, 75,  9, 75, 34, 71,  5, 88,
        7, 73, 10, 72,  5, 93, 40, 87, 12, 97, 36, 74, 22, 90, 17, 88, 20,
       76, 16, 89,  1, 78,  1, 73, 35, 83,  5, 93, 26, 75, 20, 95, 27, 63,
       13, 75, 10, 92, 13, 86, 15, 69, 14, 90, 32, 86, 15, 88, 39, 97, 24,
       68, 17, 85, 23, 69,  8, 91, 16, 79, 28, 74, 18, 83], dtype=int64)

In [10]:
x.shape

(200, 4)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler 
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [13]:
x_train

array([[ 6.14101752e-01,  1.16316000e+00, -1.31358807e+00,
         4.71130603e-01],
       [-5.79436487e-01, -8.59726954e-01,  3.07472996e-01,
        -4.80648393e-01],
       [-1.28151780e+00, -8.59726954e-01,  4.48434827e-01,
        -1.24207159e+00],
       [ 2.45509061e-01,  1.16316000e+00, -1.38406899e+00,
         1.28490165e-01],
       [ 1.21087087e+00, -8.59726954e-01, -1.85893416e-01,
         1.00412684e+00],
       [-6.32092586e-01, -8.59726954e-01,  1.08276307e+00,
        -5.18719553e-01],
       [-1.59745440e+00,  1.16316000e+00,  1.78757223e+00,
        -1.58471203e+00],
       [-4.21468191e-01,  1.16316000e+00, -8.90702575e-01,
        -2.52221434e-01],
       [ 3.33269225e-01, -8.59726954e-01,  8.71320323e-01,
         2.42703644e-01],
       [ 7.72070049e-01, -8.59726954e-01, -4.67817079e-01,
         5.85344083e-01],
       [-4.91676323e-01, -8.59726954e-01,  5.89396659e-01,
        -4.42577234e-01],
       [ 4.38581423e-01, -8.59726954e-01, -1.10214532e+00,
         3.56917124e-01],
       [ 1.49170340e+00, -8.59726954e-01,  1.66511164e-01,
         1.46098076e+00],
       [-3.53234663e-02, -8.59726954e-01, -8.20221659e-01,
        -2.37944749e-02],
       [ 8.77382246e-01,  1.16316000e+00, -3.26855248e-01,
         6.61486403e-01],
       [-1.31662187e+00, -8.59726954e-01,  1.08276307e+00,
        -1.24207159e+00],
       [-1.21130967e+00,  1.16316000e+00,  1.50564857e+00,
        -1.16592927e+00],
       [ 1.07045461e+00, -8.59726954e-01,  1.22372490e+00,
         6.99557563e-01],
       [-1.03578934e+00, -8.59726954e-01,  1.85805315e+00,
        -8.61359992e-01],
       [-7.54956817e-01, -8.59726954e-01,  8.71320323e-01,
        -6.32933033e-01],
       [ 5.61445653e-01,  1.16316000e+00,  2.55493320e-02,
         3.94988284e-01],
       [-5.28754992e-02, -8.59726954e-01,  5.89396659e-01,
        -2.37944749e-02],
       [ 1.43904730e+00, -8.59726954e-01, -4.67817079e-01,
         1.38483844e+00],
       [-1.40438204e+00, -8.59726954e-01, -2.56374332e-01,
        -1.43242739e+00],
       [ 9.47590378e-01, -8.59726954e-01, -4.49315839e-02,
         6.61486403e-01],
       [-1.23083631e-01,  1.16316000e+00,  6.59877575e-01,
        -2.37944749e-02],
       [-7.90060882e-01, -8.59726954e-01,  8.00839407e-01,
        -6.71004193e-01],
       [ 1.12311071e+00, -8.59726954e-01, -5.38297995e-01,
         7.75699882e-01],
       [-8.42716981e-01,  1.16316000e+00, -3.97336163e-01,
        -7.09075353e-01],
       [-2.28395829e-01, -8.59726954e-01,  1.15324399e+00,
        -1.38007955e-01],
       [ 7.01861917e-01, -8.59726954e-01, -2.56374332e-01,
         5.09201763e-01],
       [-1.58187697e-01, -8.59726954e-01,  2.06949589e+00,
        -6.18656348e-02],
       [ 6.66757851e-01,  1.16316000e+00, -4.67817079e-01,
         4.71130603e-01],
       [ 3.48846655e-02, -8.59726954e-01,  7.30358491e-01,
         5.23478448e-02],
       [ 7.89622082e-01,  1.16316000e+00, -9.61183491e-01,
         6.23415243e-01],
       [-1.75739730e-01, -8.59726954e-01,  8.00839407e-01,
        -9.99367947e-02],
       [ 1.75300929e-01,  1.16316000e+00,  1.92853406e+00,
         9.04190047e-02],
       [-1.49214220e+00,  1.16316000e+00, -1.15412500e-01,
        -1.54664087e+00],
       [-1.26396577e+00,  1.16316000e+00, -2.56374332e-01,
        -1.24207159e+00],
       [ 7.36965983e-01,  1.16316000e+00, -4.67817079e-01,
         5.47272923e-01],
       [ 1.54435950e+00,  1.16316000e+00, -7.49740743e-01,
         1.53712308e+00],
       [-9.30477146e-01, -8.59726954e-01,  8.00839407e-01,
        -7.85217672e-01],
       [ 6.84309884e-01,  1.16316000e+00, -1.38406899e+00,
         5.09201763e-01],
       [ 1.68477576e+00, -8.59726954e-01, -2.56374332e-01,
         2.26047512e+00],
       [ 1.57748896e-01,  1.16316000e+00,  2.06949589e+00,
         9.04190047e-02],
       [-6.49644619e-01, -8.59726954e-01,  1.99901498e+00,
        -5.18719553e-01],
       [-1.70276660e+00, -8.59726954e-01, -1.31358807e+00,
        -1.69892551e+00],
       [-7.02300718e-01,  1.16316000e+00,  1.01228215e+00,
        -5.56790713e-01],
       [ 6.49205818e-01, -8.59726954e-01,  3.77953912e-01,
         4.71130603e-01],
       [ 1.71987983e+00,  1.16316000e+00, -4.67817079e-01,
         2.48890208e+00],
       [-9.83133245e-01, -8.59726954e-01, -5.38297995e-01,
        -8.23288832e-01],
       [-1.56235033e+00,  1.16316000e+00,  1.99901498e+00,
        -1.58471203e+00],
       [ 1.66722373e+00, -8.59726954e-01,  5.89396659e-01,
         2.26047512e+00],
       [-4.56572257e-01, -8.59726954e-01,  1.50564857e+00,
        -4.04506074e-01],
       [ 1.70232779e+00, -8.59726954e-01,  4.48434827e-01,
         2.48890208e+00],
       [ 1.38639120e+00,  1.16316000e+00,  1.43516765e+00,
         1.23255380e+00],
       [ 1.33373510e+00, -8.59726954e-01, -6.08778911e-01,
         1.04219800e+00],
       [ 4.73685489e-01,  1.16316000e+00,  3.07472996e-01,
         3.94988284e-01],
       [-1.05531598e-01, -8.59726954e-01,  9.60302479e-02,
        -2.37944749e-02],
       [ 2.27957028e-01, -8.59726954e-01, -4.49315839e-02,
         1.28490165e-01],
       [ 1.03535054e+00,  1.16316000e+00, -3.26855248e-01,
         6.61486403e-01],
       [ 1.61456763e+00, -8.59726954e-01, -4.67817079e-01,
         1.61326540e+00],
       [-8.60269014e-01, -8.59726954e-01,  7.30358491e-01,
        -7.09075353e-01],
       [-1.73787066e+00,  1.16316000e+00, -1.38406899e+00,
        -1.73699667e+00],
       [-8.79795651e-02, -8.59726954e-01, -4.67817079e-01,
        -2.37944749e-02],
       [ 1.92852962e-01,  1.16316000e+00,  1.85805315e+00,
         9.04190047e-02],
       [-7.04275321e-02,  1.16316000e+00, -1.03166441e+00,
        -2.37944749e-02],
       [-6.14540553e-01,  1.16316000e+00,  1.71709131e+00,
        -4.80648393e-01],
       [ 1.19331884e+00, -8.59726954e-01, -3.97336163e-01,
         9.66055682e-01],
       [-1.01823731e+00,  1.16316000e+00, -1.03166441e+00,
        -8.61359992e-01],
       [-5.26780388e-01, -8.59726954e-01, -4.67817079e-01,
        -4.80648393e-01],
       [-8.77821047e-01, -8.59726954e-01, -5.38297995e-01,
        -7.85217672e-01],
       [-8.95373080e-01, -8.59726954e-01, -6.79259827e-01,
        -7.85217672e-01],
       [-2.45947861e-01,  1.16316000e+00,  6.59877575e-01,
        -2.52221434e-01],
       [-1.50969423e+00, -8.59726954e-01, -1.03166441e+00,
        -1.54664087e+00],
       [ 1.08800664e+00, -8.59726954e-01, -6.79259827e-01,
         6.99557563e-01],
       [-1.33417390e+00,  1.16316000e+00, -5.38297995e-01,
        -1.35628507e+00],
       [ 1.52680746e+00, -8.59726954e-01,  1.08276307e+00,
         1.53712308e+00],
       [ 6.31653785e-01, -8.59726954e-01, -6.79259827e-01,
         4.71130603e-01],
       [-1.38683000e+00,  1.16316000e+00, -2.56374332e-01,
        -1.39435623e+00],
       [-1.47459017e+00,  1.16316000e+00, -1.17262624e+00,
        -1.54664087e+00],
       [-3.68812092e-01, -8.59726954e-01, -1.10214532e+00,
        -2.52221434e-01],
       [ 8.75407643e-02,  1.16316000e+00,  7.30358491e-01,
         5.23478448e-02],
       [-8.25164948e-01, -8.59726954e-01, -5.38297995e-01,
        -6.71004193e-01],
       [ 1.73326325e-02, -8.59726954e-01, -1.10214532e+00,
         5.23478448e-02],
       [-4.03916158e-01, -8.59726954e-01,  4.48434827e-01,
        -2.52221434e-01],
       [-1.68521456e+00, -8.59726954e-01, -1.10214532e+00,
        -1.69892551e+00],
       [ 2.98165159e-01, -8.59726954e-01,  1.71709131e+00,
         1.66561324e-01],
       [ 1.14066274e+00,  1.16316000e+00,  8.00839407e-01,
         9.27984522e-01],
       [ 1.73743186e+00,  1.16316000e+00, -4.67817079e-01,
         2.90768484e+00],
       [-1.63255846e+00, -8.59726954e-01, -2.56374332e-01,
        -1.62278319e+00],
       [-5.44332421e-01,  1.16316000e+00, -1.38406899e+00,
        -4.80648393e-01],
       [-2.63499894e-01, -8.59726954e-01, -1.24310715e+00,
        -2.52221434e-01],
       [ 3.85925324e-01, -8.59726954e-01, -4.49315839e-02,
         2.42703644e-01],
       [ 9.82694444e-01, -8.59726954e-01, -8.20221659e-01,
         6.61486403e-01],
       [ 1.26352697e+00,  1.16316000e+00, -7.49740743e-01,
         1.00412684e+00],
       [ 1.00024648e+00,  1.16316000e+00, -1.15412500e-01,
         6.61486403e-01],
       [-1.40635664e-01,  1.16316000e+00, -1.45454990e+00,
        -6.18656348e-02],
       [ 1.75498389e+00,  1.16316000e+00, -6.08778911e-01,
         2.90768484e+00],
       [-1.54479830e+00, -8.59726954e-01, -2.56374332e-01,
        -1.58471203e+00],
       [ 3.50821258e-01, -8.59726954e-01,  8.00839407e-01,
         2.42703644e-01],
       [ 5.24366984e-02,  1.16316000e+00,  1.99901498e+00,
         5.23478448e-02],
       [-1.12354951e+00, -8.59726954e-01, -1.24310715e+00,
        -1.05171579e+00],
       [-7.37404784e-01,  1.16316000e+00,  2.13997681e+00,
        -6.32933033e-01],
       [-5.96988520e-01,  1.16316000e+00, -1.45454990e+00,
        -4.80648393e-01],
       [-1.72031863e+00,  1.16316000e+00, -1.24310715e+00,
        -1.73699667e+00],
       [ 3.68373291e-01,  1.16316000e+00, -8.20221659e-01,
         2.42703644e-01],
       [ 1.10555867e+00,  1.16316000e+00, -1.38406899e+00,
         7.75699882e-01],
       [-1.00068528e+00,  1.16316000e+00,  6.59877575e-01,
        -8.23288832e-01],
       [ 1.05092797e-01, -8.59726954e-01, -1.24310715e+00,
         5.23478448e-02],
       [ 5.78997686e-01, -8.59726954e-01, -9.61183491e-01,
         4.33059444e-01],
       [ 1.29863104e+00,  1.16316000e+00, -1.85893416e-01,
         1.00412684e+00],
       [-1.43948610e+00,  1.16316000e+00, -1.31358807e+00,
        -1.50856971e+00],
       [-1.07089341e+00, -8.59726954e-01, -1.85893416e-01,
        -8.99431152e-01],
       [ 5.96549719e-01, -8.59726954e-01, -5.38297995e-01,
         4.33059444e-01],
       [-8.07612915e-01,  1.16316000e+00,  1.43516765e+00,
        -6.71004193e-01],
       [ 1.01779851e+00, -8.59726954e-01, -6.08778911e-01,
         6.61486403e-01],
       [ 5.08789555e-01,  1.16316000e+00,  1.43516765e+00,
         3.94988284e-01],
       [-1.14110154e+00, -8.59726954e-01,  7.30358491e-01,
        -1.05171579e+00],
       [-1.24641374e+00, -8.59726954e-01,  9.60302479e-02,
        -1.20400043e+00],
       [ 2.63061094e-01, -8.59726954e-01, -1.45454990e+00,
         1.66561324e-01],
       [ 9.12486312e-01,  1.16316000e+00,  2.55493320e-02,
         6.61486403e-01],
       [-1.19375764e+00, -8.59726954e-01, -1.24310715e+00,
        -1.16592927e+00],
       [ 1.17576681e+00,  1.16316000e+00,  2.36992080e-01,
         9.66055682e-01],
       [ 4.91237522e-01,  1.16316000e+00,  9.60302479e-02,
         3.94988284e-01],
       [ 1.35128714e+00,  1.16316000e+00,  1.36468673e+00,
         1.04219800e+00],
       [-1.17620561e+00,  1.16316000e+00,  1.01228215e+00,
        -1.05171579e+00],
       [ 7.54518016e-01, -8.59726954e-01, -7.49740743e-01,
         5.85344083e-01],
       [ 1.22842290e+00,  1.16316000e+00, -4.67817079e-01,
         1.00412684e+00],
       [ 8.42278180e-01, -8.59726954e-01, -4.67817079e-01,
         6.23415243e-01],
       [-1.22886171e+00, -8.59726954e-01, -1.10214532e+00,
        -1.20400043e+00],
       [-2.19400412e-04,  1.16316000e+00, -1.31358807e+00,
         1.42766850e-02],
       [-2.98603960e-01,  1.16316000e+00,  1.99901498e+00,
        -2.52221434e-01],
       [-3.51260059e-01, -8.59726954e-01,  7.30358491e-01,
        -2.52221434e-01],
       [ 2.80613127e-01, -8.59726954e-01, -1.38406899e+00,
         1.66561324e-01],
       [ 8.59830213e-01, -8.59726954e-01, -3.26855248e-01,
         6.61486403e-01],
       [ 1.64967170e+00, -8.59726954e-01, -4.49315839e-02,
         1.99397700e+00],
       [-4.74124290e-01, -8.59726954e-01,  1.50564857e+00,
        -4.04506074e-01],
       [-3.86364125e-01,  1.16316000e+00,  9.60302479e-02,
        -2.52221434e-01],
       [-1.29906984e+00,  1.16316000e+00, -6.79259827e-01,
        -1.24207159e+00],
       [ 1.15821477e+00, -8.59726954e-01, -1.85893416e-01,
         9.27984522e-01],
       [-3.16155993e-01,  1.16316000e+00, -4.49315839e-02,
        -2.52221434e-01],
       [ 1.56191153e+00, -8.59726954e-01,  1.66511164e-01,
         1.61326540e+00],
       [ 1.31618307e+00, -8.59726954e-01,  9.41801239e-01,
         1.04219800e+00],
       [ 1.59701560e+00, -8.59726954e-01, -3.26855248e-01,
         1.61326540e+00],
       [-1.05334138e+00, -8.59726954e-01, -1.31358807e+00,
        -8.99431152e-01],
       [-7.19852751e-01, -8.59726954e-01, -8.20221659e-01,
        -5.56790713e-01],
       [ 7.19413950e-01, -8.59726954e-01,  1.29420582e+00,
         5.47272923e-01],
       [-1.93291763e-01, -8.59726954e-01, -3.26855248e-01,
        -9.99367947e-02],
       [-5.09228356e-01,  1.16316000e+00,  2.21045773e+00,
        -4.42577234e-01],
       [-2.10843796e-01, -8.59726954e-01, -1.17262624e+00,
        -1.38007955e-01],
       [-1.10599748e+00, -8.59726954e-01,  2.36992080e-01,
        -1.01364463e+00],
       [-1.36927797e+00,  1.16316000e+00, -9.61183491e-01,
        -1.39435623e+00],
       [-1.57990236e+00, -8.59726954e-01, -6.08778911e-01,
        -1.58471203e+00],
       [ 6.99887313e-02,  1.16316000e+00, -8.90702575e-01,
         5.23478448e-02],
       [-5.61884454e-01, -8.59726954e-01,  2.06949589e+00,
        -4.80648393e-01],
       [ 1.63211966e+00,  1.16316000e+00, -3.97336163e-01,
         1.99397700e+00],
       [ 3.15717192e-01, -8.59726954e-01,  7.30358491e-01,
         1.66561324e-01],
       [-9.12925113e-01, -8.59726954e-01, -8.20221659e-01,
        -7.85217672e-01],
       [ 1.28107900e+00,  1.16316000e+00, -1.85893416e-01,
         1.00412684e+00]])

In [14]:
x.shape

(200, 4)

In [15]:
dataset.head()

   CustomerID  Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1      1   19                  15                      39
1           2      1   21                  15                      81
2           3      0   20                  16                       6
3           4      0   23                  16                      77
4           5      0   31                  17                      40

In [16]:
from tensorflow.keras.models import Sequential #-used to initialize the model.
from tensorflow.keras.layers import Dense #- used to add layers of ANN

In [17]:
con=Sequential()

In [18]:
con.add(Dense(4,kernel_initializer="random_uniform",activation='relu'))

WARNING:tensorflow:From C:\Users\Harshita\Anaconda3\lib\site-packages\tensorflow\python\keras\initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [19]:
con.add(Dense(8,kernel_initializer="random_uniform",activation='relu'))

In [20]:
con.add(Dense(1,kernel_initializer="random_uniform",activation='relu'))

In [21]:
con.compile("adam","mean_squared_error", metrics=['mse'])

In [22]:
con.fit(x_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
160/160 [==============================] - 0s 803us/sample - loss: 3103.4248 - mean_squared_error: 3103.4248
Epoch 2/10
160/160 [==============================] - 0s 62us/sample - loss: 3102.9000 - mean_squared_error: 3102.9001
Epoch 3/10
160/160 [==============================] - 0s 41us/sample - loss: 3102.3370 - mean_squared_error: 3102.3369
Epoch 4/10
160/160 [==============================] - 0s 75us/sample - loss: 3101.7643 - mean_squared_error: 3101.7642
Epoch 5/10
160/160 [==============================] - 0s 57us/sample - loss: 3101.1615 - mean_squared_error: 3101.1616
Epoch 6/10
160/160 [==============================] - 0s 38us/sample - loss: 3100.5244 - mean_squared_error: 3100.5247
Epoch 7/10
160/160 [==============================] - 0s 64us/sample - loss: 3099.8438 - mean_squared_error: 3099.8435
Epoch 8/10
160/160 [==============================] - 0s 67us/sample - loss: 3099.1293 - mean_squared_error: 3099.1294
Epoch 9/10
160/160 [==============================] - 0s 87us/sample - loss: 3098.3346 - mean_squared_error: 3098.3345
Epoch 10/10
160/160 [==============================] - 0s 37us/sample - loss: 3097.4934 - mean_squared_error: 3097.4934

In [23]:
ypred=con.predict(x_test)

In [24]:
ypred

array([[0.0653314 ],
       [0.07125418],
       [0.0672522 ],
       [0.06601312],
       [0.07158211],
       [0.07340042],
       [0.06305469],
       [0.06939493],
       [0.06546881],
       [0.06998922],
       [0.06257599],
       [0.06744286],
       [0.07385197],
       [0.07015818],
       [0.06674798],
       [0.06308299],
       [0.06251508],
       [0.06798132],
       [0.06303347],
       [0.06706291],
       [0.07404256],
       [0.06854442],
       [0.06306249],
       [0.07016984],
       [0.06879756],
       [0.06680331],
       [0.07244992],
       [0.07350001],
       [0.06726364],
       [0.06427378],
       [0.06379843],
       [0.06460224],
       [0.06926925],
       [0.06689396],
       [0.06440952],
       [0.07509321],
       [0.06719639],
       [0.06369212],
       [0.06487294],
       [0.06831186]], dtype=float32)

In [25]:
y_test

array([29, 13, 46, 42, 69, 15, 76, 36, 15, 20, 55, 77, 32, 16, 51, 94, 92,
        9, 73, 47, 88, 97, 65, 73, 56, 91, 90, 97, 58, 28, 35, 41, 17, 54,
        5, 85, 75, 40, 44, 50], dtype=int64)

In [26]:
dataset.head()

   CustomerID  Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1      1   19                  15                      39
1           2      1   21                  15                      81
2           3      0   20                  16                       6
3           4      0   23                  16                      77
4           5      0   31                  17                      40

In [27]:
yp=con.predict(sc.transform([[2,1,21,15]]))

In [28]:
yp

array([[0.06348212]], dtype=float32)